MODEL:

TRAIN:
  train_data_dir: [
    #'./dataset/mydata/train1',
    #'./dataset/mydata/train2',
    #'./dataset/mydata/train3',
    #'./dataset/mydata/train4',
    './dataset/mydata/train5',
    './dataset/mydata/train6',
  ]
  batch_size: 512
  width: 128
  height: 32
  epochs: 50000
  cuda: True
  ngpu: 1
  workers: 32
  resume: ''
  ckpt_dir: './ckpt/'
  voc_type: 'all'
  saveInterval: 800
  displayInterval: 50
  adadelta: False
  lr: 0.00007
  adam: True
  beta1: 0.5
  manualSeed: 1234
  max_len: 100
  keep_ratio: False
  down_sample_scale: 2

  VAL:
    val_data_dir: [
    ]
    n_vis: 10
    vis_dir: 'demo'
    valInterval: 800
    rec_pretrained: ''
    moran_pretrained: ''
    crnn_pretrained: ''

TEST:
  checkpoint: ''
  test_data_dir: [
    ''
  ]

CONVERT:
  image_dir:
  lmdb_dir:
  n_convert: 10
